version: '3.4'

services:
  motorentalservice.api:
    image: ${DOCKER_REGISTRY-}motorentalserviceapi
    container_name: motorentalservice.api
    build:
      context: .
      dockerfile: MotoRentalService.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on: 
      - db
      - rabbitmq

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: MotoRentalDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p4ssw0rd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "8080:15672"

volumes:
  postgres_data: